[Update] Add Domain Shortguide
linode/docs pull request #3690
Opened 2020-10-09 23:48 UTC by rsyracuse

AXFR Update

2020-10-09 23:55 UTC, nmelehan commented
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 5c49c12437d4e276ec2b04428cb9a682e19f531d

https://deploy-preview-3690--nostalgic-ptolemy-b01ab8.netlify.app

2020-10-13 19:11 UTC, andystevensname requested changes

2020-10-13 19:11 UTC, andystevensname commented on docs/platform/manager/dns-manager-add-domain-shortguide/index.md
> +In order for Linode's DNS servers to function as slaves,your DNS master server must notify and allow AXFR requests from the following IP addresses:
space between `slaves,` and `your`

2020-10-13 19:11 UTC, andystevensname commented on docs/platform/manager/dns-manager-add-domain-shortguide/index.md
> +In order for Linode's DNS servers to function as slaves,your DNS master server must notify and allow AXFR requests from the following IP addresses:
Looks like this Note isn't rendering for some reason: https://deploy-preview-3690--nostalgic-ptolemy-b01ab8.netlify.app/platform/manager/dns-manager/#add-a-domain

2020-10-13 19:11 UTC, andystevensname commented on docs/platform/manager/dns-manager-add-domain-shortguide/index.md
> +On **December 15th, 2020** the IP address `75.127.96.10` will be replaced with the IP address `74.207.225.10`. While both IP addresses currently provide AXFR support, users will need to replace `75.1
space between `2020,` and `for`

2020-10-19 17:56 UTC, merged