[Update] Copy a Disk Over SSH
linode/docs pull request #3708
Opened 2020-10-21 14:39 UTC by rsyracuse

Clarification on copying/download language and process

2020-10-21 14:46 UTC, nmelehan commented
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 28e68a758b13b9932df4901e0648642dc0531e3b

https://deploy-preview-3708--nostalgic-ptolemy-b01ab8.netlify.app

2020-11-24 15:32 UTC, leslitagordita requested changes

2020-11-24 15:32 UTC, leslitagordita commented on docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
> +This guide was written to support Downloading a disk over SSH from a  **Linode**, which will be used to Create and Send an image to a separate receiving system that you personally own. This means tha
* Please remove usage of the future tense
* Downloading, Receiving System, and Origin Linode do not need to be capitalized.
* Rewrite suggestion for the first sentence: This guide shows you how to download a Linode's disk image over SSH to a separate receiving system, like a personal computer.

2020-11-24 15:32 UTC, leslitagordita commented on docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
> +While this guide has been written to accommodate computers running Linux as their operating system, if the receiving system is Microsoft Windows, there are multiple SSH solutions available such as [C
missing the word running: "if the receiving system is running Microsoft Windows,"

2020-11-24 15:32 UTC, leslitagordita commented on docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
> +1.  Prepare the Receiving System that will be downloading the disk image by verifying that SSH is installed. Most Linux/Unix-like systems include OpenSSH in their package base by default.
* Receiving System doesn't need to be capitalized 
* Please remove future tense.

2020-11-24 15:32 UTC, leslitagordita commented on docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
> +You may want to upload your disk image to a new server. For example, if you previously downloaded your Linode disk and deleted the Linode to halt billing on it, you can create a new Linode at a later
Remove future tense.

2020-11-24 16:48 UTC, leslitagordita commented on docs/guides/platform/disk-images/copying-a-disk-image-over-ssh/index.md
> +In some cases, it is necessary to upload your disk image to a new server. For example, if you previously downloaded your Linode disk and deleted the Linode to halt billing on it, you can create a new
New Linode --> new Linode
default Primary --> default primary
Swap Disk --> swap disk

2020-11-24 17:36 UTC, leslitagordita approved these changes

2020-11-24 17:36 UTC, merged