Initial draft of Magento on CentOS 8 guide
linode/docs pull request #3815
Opened 2020-11-29 20:48 UTC by JeffreyNovotny

This is a user guide for hot to install Magento 2.4 on CentOS 8. It should contain the root index.md document as well as 7 images in .png format.

2020-11-29 20:52 UTC, nmelehan commented
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit f1d2c11a4274751e12ef92e8a560690858765b6d

https://deploy-preview-3815--nostalgic-ptolemy-b01ab8.netlify.app

2021-02-24 03:41 UTC, Rajakavitha1 requested changes
Step 3 : sudo dnf update && sudo dnf upgrade

2021-02-24 03:44 UTC, Rajakavitha1 requested changes
The recommendation of a 4GB Linode can go in the before you begin you begin section. You dont want the users to get started and securing a 2GB Linode, later to realize that the requirement was a $GB

2021-02-24 03:45 UTC, Rajakavitha1 requested changes
The command to check the version of Apache that worked on a centos8 Linode was ``` httpd -v``` was not able to check the version with the command listed
<img width="289" alt="Screenshot 2021-02-24 at 12 16 18 PM" src="https://user-images.githubusercontent.com/37059749/108959238-256eed80-769a-11eb-8be0-15af9897e0c0.png">

The list of modules required is listed in the output format.  This should be a bulleted list or a comma separated list.
<img width="209" alt="Screenshot 2021-02-24 at 12 22 39 PM" src="https://user-images.githubusercontent.com/37059749/108959867-0b81da80-769b-11eb-88d3-500d0eeb6bf8.png">

The output should be:
<img width="345" alt="Screenshot 2021-02-24 at 12 25 39 PM" src="https://user-images.githubusercontent.com/37059749/108960131-6f0c0800-769b-11eb-8a85-ed7cbebbe1c4.png">

Step 3. Install missing modules. Please confirm what should be the command because it results in the following error message:
<img width="583" alt="Screenshot 2021-02-24 at 12 29 05 PM" src="https://user-images.githubusercontent.com/37059749/108960508-0a04e200-769c-11eb-97ad-8431f325a46e.png">


The command to check if ssl_module is installed ```sudo httpd -t -D DUMP_MODULES | grep ssl```
The command to install ssl_module is ``` sudo dnf install mod_ssl```

2021-02-24 03:48 UTC, Rajakavitha1 requested changes
In this guide we also need to provide  the links to the guides that have instructions to install apache on Centos 8, MySQL on Centos, php on Centos 8 in the beginning of the respective sections. You may also want to shorten the length of the guide by not repeating the steps that are already there in the respective guides.

2021-02-24 06:39 UTC, Rajakavitha1 requested changes
After creating the key, edit the /etc/httpd/conf.d/ssl.conf file. Set the values of SSLCertificateFile and SSLCertificateKeyFile to reference the key you created: However, the file name reads: File: /etc/httpd/conf.d/vhost.conf

2021-02-24 11:24 UTC, Rajakavitha1 reviewed
Enable the PHP Opcache for better performance. This setting can be found and modified in opcache.ini.

opcach.ini was not found and had to install it with ```sudo dnf install opcache.ini```
<img width="564" alt="Screenshot 2021-02-24 at 4 40 55 PM" src="https://user-images.githubusercontent.com/37059749/108993741-fae45b00-76c0-11eb-996d-6592a096397f.png">

2021-02-25 10:22 UTC, Rajakavitha1 requested changes
Please make installing LEMP on CentOS8 Linode guide as a prerequisite in the before you begin section or provide the links to individual Apache, Msql, PHP 7.4  guides in the prerequisite section of Magento.

2021-02-25 10:22 UTC, Rajakavitha1 commented on docs/guides/websites/ecommerce/install-magento-2-4-on-centos-8/index.md
> +Magento recommends the use of PHP 7.4.0 or higher.
This is a requirement not a recommendation:

Magento supports PHP 7.3.0 or later. Please read https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html

2021-03-05 18:52 UTC, andystevensname approved these changes

2021-03-05 18:53 UTC, andystevensname commented
Closed in favor of https://github.com/linode/docs/pull/4081

2021-03-05 18:53 UTC, closed without merging