Initial draft of Redis on Ubuntu 20.04 guide
linode/docs pull request #3891
Opened 2021-01-10 15:57 UTC by JeffreyNovotny

The preview for the Redis on Ubuntu 20.04 guide is ready.

2021-01-10 16:05 UTC, nmelehan commented
:heavy_check_mark: Deploy preview for *nostalgic-ptolemy-b01ab8* ready!


:hammer: Explore the source changes: f18c82c97f54cea2566843046a8c80a4a47e6f7d

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/5ffb240041ca190007be3c00](https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/5ffb240041ca190007be3c00?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-3891--nostalgic-ptolemy-b01ab8.netlify.app](https://deploy-preview-3891--nostalgic-ptolemy-b01ab8.netlify.app?utm_source=github&utm_campaign=bot_dp)

2021-01-22 14:26 UTC, andystevensname requested changes

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +        fido
Again, the  output tag here would help distinguish this from a command.

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +Beginning with version 6, Redis maintains multi-user security through an ACL. Additionally, you can create a default user password. A default password might be sufficient for a single user. However,
For lesser known acronyms we define them first, then abbreviate them: "...through an  access control list, or ACL."

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +        (error) NOAUTH Authentication required.
Use the output tag here.

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +## Configuring a Password for Redis
This second level heading, and the ACL second level heading further down the guide, might work well as H3s organized under an H2 of "Securing Redis" or something similar.

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +        (error) NOPERM this user has no permissions to run the 'set' command or its subcommand
Use the output tag.

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +Redis supports 2 persistence options:
two instead of 2

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +
Maybe a brief sentence or two on  why persistence is so important for Redis (because everything is stored in memory, etc)

2021-01-22 14:26 UTC, andystevensname commented on docs/guides/databases/redis/install-and-configure-redis-on-ubuntu-20/index.md
> +*   AOF persistence appends every write operation to a log. Redis replays these transactions at startup to restore the database state. You can configure AOF persistence in the `redis.conf` file with
What do  RDB and AOF stand for? Does that matter here?

2021-07-01 18:53 UTC, leslitagordita commented
Closing in preference for: https://github.com/linode/docs/pull/4465

2021-07-01 18:53 UTC, closed without merging