Initial draft of NVM installation and usage guide
linode/docs pull request #3903
Opened 2021-01-14 13:07 UTC by JeffreyNovotny

Guide for NVM installation and usage guide.

2021-01-14 13:12 UTC, nmelehan commented
:heavy_check_mark: Deploy preview for *nostalgic-ptolemy-b01ab8* ready!


:hammer: Explore the source changes: efb0ef73d0e0c9268485a8a525ddc077ca47220e

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/6000422d907c650008c4fc3d](https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/6000422d907c650008c4fc3d?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-3903--nostalgic-ptolemy-b01ab8.netlify.app](https://deploy-preview-3903--nostalgic-ptolemy-b01ab8.netlify.app?utm_source=github&utm_campaign=bot_dp)

2021-01-27 18:33 UTC, andystevensname requested changes

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        nvm
Use  the {{< output >}} tag to denote output

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        Now using node v15.5.1 (npm v7.3.0)
Use the output tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        v5.12.0
Use  the output tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        v13.10.1
Use the  output   tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        Now using node v14.15.4
Use  the output tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        v14.15.4
Output tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        Running node v15.5.1 (npm v7.3.0)
Output tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        maintenance -> 13.10.1 (-> v13.10.1)
Use output  tag

2021-01-27 18:33 UTC, andystevensname commented on docs/guides/development/nodejs/how-to-install-use-node-version-manager-nvm/index.md
> +        default -> 14 (-> v14.15.4)
Use output tag

2021-02-09 21:18 UTC, rsyracuse approved these changes

2021-02-12 12:31 UTC, andystevensname approved these changes

2021-02-12 12:31 UTC, merged