[Update] farmOS - fixes
linode/docs pull request #3995
Opened 2021-02-09 16:37 UTC by bbiggerr

2021-02-09 16:41 UTC, nmelehan commented
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 4eb5e9bf037dd2d11d4fde07b35af91d3fac57c4

https://deploy-preview-3995--nostalgic-ptolemy-b01ab8.netlify.app

2021-02-11 15:29 UTC, andystevensname requested changes

2021-02-11 15:29 UTC, andystevensname commented on docs/guides/applications/project-management/install-farmos/index.md
>         sudo chmod 644 sites/default
These lines need one more space for the indent, it looks like.

2021-02-11 15:29 UTC, andystevensname commented on docs/guides/applications/project-management/install-farmos/index.md
> +    ![Add user](Adduser.png)
Image does not show up in the guide, might be a spacing issue.

2021-02-11 15:29 UTC, andystevensname commented on docs/guides/applications/project-management/install-farmos/index.md
> +    ![People screen](peoplescreen.png)
Image does not show up in guide, might be a spacing issue.

2021-02-12 12:33 UTC, andystevensname approved these changes

2021-02-12 13:03 UTC, merged