[Update] What is Longview
linode/docs pull request #4250
Opened 2021-04-23 14:32 UTC by rsyracuse

Re-organizing, mentioning fedora updates

2021-04-23 14:36 UTC, nmelehan commented
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit b4db5d1b2354da0eed82ed95ca0329a32ee5dbaa

https://deploy-preview-4250--nostalgic-ptolemy-b01ab8.netlify.app

2021-05-03 19:44 UTC, andystevensname commented on docs/guides/platform/monitoring/what-is-longview/index.md
The indentation in the section is a bit wonky, @rsyracuse can you take a look?

2021-05-03 19:44 UTC, andystevensname requested changes
Please check indentation under noted section

2021-05-04 11:29 UTC, andystevensname approved these changes

2021-05-04 11:29 UTC, merged