*Do not merge* Continuous Deployment with LKE Series
linode/docs pull request #4281
Opened 2021-05-04 12:18 UTC by wildmanonline

These are the guides that go along with the **Continuous Deployment with LKE** presentation. This branch is still under development but will be released by Thursday.

2021-05-04 12:22 UTC, nmelehan commented
Deploy preview for *nostalgic-ptolemy-b01ab8* ready!

Built with commit 644ff83d0011ad4a6a5ef9ed96b28dd1eb391c80

https://deploy-preview-4281--nostalgic-ptolemy-b01ab8.netlify.app

2021-05-05 21:24 UTC, wildmanonline commented
Main page of this new series can be found here: https://deploy-preview-4281--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/lke-continuous-deployment-series/

2021-05-06 13:39 UTC, leslitagordita requested changes
@wildmanonline these are missing `h1_title`, `enable_h1: true`, and `og_description` front matter. Everything else looked good!

2021-05-06 13:58 UTC, leslitagordita approved these changes

2021-05-06 14:54 UTC, merged