[New] Securing an LKE Cluster through User Permissions and RBAC
linode/docs pull request #4397
Opened 2021-06-10 14:13 UTC by rsyracuse

2021-06-10 14:17 UTC, nmelehan commented
:heavy_check_mark: Deploy Preview for *nostalgic-ptolemy-b01ab8* ready!


:hammer: Explore the source changes: 6c38e7d9409a912e079b9a610baeb695d7e91ace

:mag: Inspect the deploy log: [https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/60c21e034a14cb000700b7f0](https://app.netlify.com/sites/nostalgic-ptolemy-b01ab8/deploys/60c21e034a14cb000700b7f0?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-4397--nostalgic-ptolemy-b01ab8.netlify.app](https://deploy-preview-4397--nostalgic-ptolemy-b01ab8.netlify.app?utm_source=github&utm_campaign=bot_dp)

2021-06-11 14:02 UTC, andystevensname requested changes

2021-06-11 14:02 UTC, andystevensname commented on docs/guides/kubernetes/securing-an-LKE-cluster/index.md
> +Now that the user has been successfully installed, the users `kubeconfig` file may be exported for other users to use from their own `kubectl` clients, and the user can access the cluster with the li
"Now that the user has been successfully installed, the **user's**..." (added apostrophe)

2021-06-11 18:33 UTC, andystevensname approved these changes

2021-06-11 18:36 UTC, merged