Optimization for nodejs and nano pages
linode/docs pull request #4979
Opened 2021-12-13 21:21 UTC by lucianmatt

2021-12-14 19:17 UTC, andystevensname requested changes

2021-12-14 19:17 UTC, andystevensname commented on docs/guides/tools-reference/tools/use-nano-text-editor-commands/index.md
> +You can make changes to the file using the Nano eidtor. You may exit the file by pressing *Ctrl + X*. It prompts you to save the file and name it before you exit.
editor spelled wrong

2022-01-14 13:46 UTC, andystevensname approved these changes

2022-01-14 16:51 UTC, wildmanonline approved these changes

2022-01-14 18:09 UTC, merged