Jan11 Description Updates
linode/docs pull request #5046
Opened 2022-01-11 23:10 UTC by mmthomaslinode

More updates from the Victorious sheet.

2022-01-12 17:58 UTC, andystevensname requested changes

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/applications/configuration-management/puppet/use-puppet-modules-to-create-a-lamp-stack/index.md
> +description: 'With this guude, you will learn how to efficiently use Puppet modules to manage files and services, create templates, and store data in Hiera on Ubuntu 14.04 LTS.'
guide misspelled

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/databases/mysql/connect-metabase-with-mysql-for-data-exploration/index.md
> +description: 'This guide shows you how to connect Metabase, a datae xploration tool that makes analytics easy, to a local MySQL server and deploy through a reverse proxy on NGINX.'
data exploration

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/databases/mysql/how-to-create-source-replica-replication-in-mysql/index.md
> +description: 'This guide explains how to configure source-replica data replication in the popula rmySQL database application.'
popular MySQL

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/development/javascript/authenticating-over-websockets-jwt/index.md
> +description: "In this guide, you learn more about both WebSockets and JSON Web Tokens will also follow an example showing you how to use them together in your app."
This sentence construction is not correct. You could write something like "...JSON Web Tokens. Follow an example..."

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/development/javascript/how-to-authenticate-using-jwt/index.md
> +description: "In this guide, you will learn key concetps behing the concept of JSON Web Tokens (JWTs) and how they provide a compact and secure standard for sending information, especially on the web
concepts behind JSON Web Tokens

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/game-servers/host-a-terraria-server-on-your-linode/index.md
> +description: 'In this guide, you will learn how to install and configure a Terraria, a two-dimensional sandbox game similar to Minecraft, on a Linode.'
configure Terraria (no a)

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/platform/manager/an-overview-of-the-linode-cloud-manager/index.md
> +description: 'This guide provides an overview of the Linode Cloud Manager and covers each specific features that you may need help finding.'
covers specific features (no each)

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/platform/marketplace/chevereto-marketplace-app/index.md
> +description: "This guide shows you how to install chevereto, a modern image sharing solution with drag-and-drop upload experience and more using the Linode One-Click Marketplace."
Capitalize Chevereto

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/security/basics/docker-security-essentials/index.md
> +description: "This guide will show you the basics of securing Docker containers, including managing user access, preventing privliges escalations, and more."
spelling of privilege (singular)

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/security/basics/how-to-configure-automated-security-updates-centos/index.md
> +description: "In this tutorial, you will learn how to configure automated updates on CentOS using the dnf-automatic tool or the COckpit web application."
No cap O in Cockpit

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/security/basics/how-to-configure-automated-security-updates-ubuntu/index.md
> +description: "In this tutorial, you will learn how to configure automated updates on Ubuntu, by using the dns-automatic tool or the Cockpit web application."
Is it dnf-automatic tool, or dns-automatic?

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/web-servers/apache/how-to-configure-http-2-on-apache/index.md
> +description: 'In this tutorial, you will learn how to configure HTTP/2 on Apache using Debian.'
configure HTTP/2 using Apache on Debian

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/websites/cms/wordpress/configuring-wordpress/index.md
> +description: "This guide shows you how to conifugure your WordPress site with additional utilities, such as installing PHP GD extensions and prettifying your permalinks."
spelling of configure

2022-01-12 17:58 UTC, andystevensname commented on docs/guides/websites/lms/how-to-install-canvas-on-debian-10/index.md
> +description: 'This guide will show you how to install the popula rlearning management system Canvas on Debian 10.'
popular learning

2022-01-13 15:52 UTC, andystevensname approved these changes

2022-02-07 19:29 UTC, wildmanonline approved these changes

2022-02-07 19:44 UTC, andystevensname approved these changes

2022-02-07 19:44 UTC, andystevensname commented on docs/guides/applications/containers/access-an-apache-web-server-inside-a-lxd-container/index.md
> +description: "This guide will show you how to install and configure Apache Web Server inside of LXD server and then direct web traffic to the container."
LXD container

2022-02-07 20:17 UTC, merged