[Update] Configuring IP Failover on a Compute Instance
linode/docs pull request #5290
Opened 2022-03-17 13:22 UTC by wildmanonline

- Identified Legacy and BGP IP Sharing data centers
- Added IP failover instructions for BGP using [lelastic](https://github.com/linode/lelastic)

Preview: [Configuring IP Failover on a Compute Instance](https://deploy-preview-5290--nostalgic-ptolemy-b01ab8.netlify.app/docs/guides/ip-failover/#configure-failover)

2022-03-21 19:25 UTC, andystevensname requested changes

2022-03-21 19:25 UTC, andystevensname commented on docs/guides/networking/linode-network/ip-failover/index.md
> +1. Add an additional IPv4 address to one of the Compute Instances. See the [Managing IP Addresses](/docs/guides/managing-ip-addresses/#adding-an-ip-address) guide for instructions. Make a note of the
Suggestion: "...make use of the newly assigned address..."

2022-03-21 19:25 UTC, andystevensname commented on docs/guides/networking/linode-network/ip-failover/index.md
> +    1.  Add the shared ip address to the loopback interface:
Caps on IP

2022-03-21 19:25 UTC, andystevensname commented on docs/guides/networking/linode-network/ip-failover/index.md
> +        Once configured, the shared IP address is routed to the primary system. If that system is inaccessible, it fails over to the secondary system *until* the primary system becomes available agai
"It" at the beginning of the third sentence is weak here. Could be "the primary systems still fails over to the secondary system..."

2022-03-21 20:16 UTC, andystevensname approved these changes

2022-03-22 12:27 UTC, nmelehan approved these changes

2022-03-24 14:45 UTC, merged