Guide on Backing Up Compute Instances to Object Storage
linode/docs pull request #6146
Opened 2023-03-08 18:05 UTC by nasanos

Submitting the guide on backing up a compute instance to object storage.

2023-08-30 05:25 UTC, wildmanonline requested changes
I started a review on this and left a few comments, but I had a question about the purpose of using rsync. If the goal is incremental backups, how does this compare to using the `--listed-incremental` option of the tar command? Perhaps rsync is better, but it creates additional complexity and additional commands. If its possible to only use tar without performance issues or a reduction in functionality over rsync, I'd favor just using tar here.

Also, the sections are positioned as tar vs rsync instead of the real differentiators: Full backups (using tar) and Incremental backups (currently using rsync and tar but perhaps only tar is needed).

2023-08-30 05:25 UTC, wildmanonline commented on docs/guides/platform/object-storage/backing-up-compute-instance-to-object-storage/index.md
> +The rsync utility provides robust and versatile options for copying data from one location to another. Here, rsync is used precisely and just to do that, but rsync also includes the noteworthy featur
This sentence could generally be improved:

> Here, rsync is used precisely and just to do that, but rsync also includes the noteworthy feature of incremental backups.

2023-08-30 16:59 UTC, nasanos commented
@wildmanonline I don't recall whether or not I came across the `--listed-incremental` option at the time. And just now in a few small-scale tests, the tar command seems to work just fine alone, so it would be great if we could approach it as you've suggested.

But that said, I seem to recall my motivation for rsync coming after I ran into limits with tar's efficiency. I'd need to run a full-scale test with it again, but I think that tar struggled or failed with incremental backups on the system scale, due to the size and duration, even on a fresh compute instance.

2023-08-30 17:21 UTC, nasanos commented on docs/guides/platform/object-storage/backing-up-compute-instance-to-object-storage/index.md
> +```command
Looks like this is possible. The root directory is already specified as the source via the `/` at the end of the `tar` command. And, after a little digging, it does look like specific archive file locations can be given after the `-f` option. So, I made this variant on the command which should forgo the need for the `cd` and `mv` commands:

```
sudo tar -vcpzf /tmp/backup.tgz --exclude='backup.tgz' --exclude='dev/*' --exclude='proc/*' --exclude='sys/*' --exclude='tmp/*' --exclude='run/*' --exclude='mnt/*' --exclude='media/*' --exclude='lost+found/*' /
```

2023-08-31 19:58 UTC, nasanos reviewed
Reviewed the requested changes, and submitted a new commit with corresponding edits.

2023-09-08 13:26 UTC, wildmanonline approved these changes

2023-09-12 18:24 UTC, merged