[Update] Deploy WordPress through the Linode Marketplace
linode/docs pull request #6771
Opened 2023-12-14 19:02 UTC by timzl

Clarified instructions on file path for password reset.

2023-12-18 05:40 UTC, Rajakavitha1 requested changes

2023-12-18 05:40 UTC, Rajakavitha1 commented on docs/products/tools/marketplace/guides/wordpress/index.md
> +    cd /var/www/[domain]/public_html
```suggestion
    cd /var/www/example.com/public_html
```
Please see, https://www.linode.com/docs/guides/linode-writers-formatting-guide/#placeholders

2023-12-18 05:41 UTC, Rajakavitha1 commented on docs/products/tools/marketplace/guides/wordpress/index.md
> +    cd /var/www/[domain]/public_html
Thank you for the PR @timzl

2023-12-19 19:08 UTC, wildmanonline approved these changes

2024-01-03 20:02 UTC, wildmanonline approved these changes

2024-01-03 20:07 UTC, wildmanonline commented
@Rajakavitha1 it appears that we are blocked from merging this. Can you approve the change that you requested?

2024-01-05 09:17 UTC, Rajakavitha1 approved these changes
LGTM!

2024-01-05 09:17 UTC, merged